### ISSUE TITLE
Перевод главного файла

### ISSUE THREAD

**Issue by bapmeh** [Alexanik/FoundryVTT-dnd5e-lang-ru-RU#2]
Сокращать слова или сделать шрифт поменьше для русского языка?
Что делать с падежами?

**Comment by Snuux** [comment]
С падежами - пока думаю ничего не нужно. Насчет шритфа - это нужно css правила поменять, чтобы отменить принудительный отступ и были переносы там где заходит за границы. Или расширить само окошко из которого вылезают проблемы. В общем всё фиксица в css. Теперь осталось решить - как правильно править css из нашего модуля перевода.

**Comment by bapmeh** [comment]
Хорошо, спасибо! Давайте решать )
